### ISSUE TITLE
[v1.0.2] Rats still spawning incorrectly?

### ISSUE THREAD

**Issue by IdrisQe** [Ladysnake/Rats-Mischief#10]
So despite having v1.0.2 installed since I made this latest world, ever since I placed down my bed and some barrels and chests and stuff in my home, I've suddenly started getting rats spawning around outside... I think the detection may be considering my house to be an abandoned village due to there being beds but no villagers, or something. I've also observed them spawning around the Dungeons added by Castle Dungeons mod, which spawn with beds inside some rooms, so I think beds may still be the issue.

They aren't spawning in occupied villages anymore, though.

**Comment by doctor4t** [comment]
Testing this in a world without structures, no rats spawn, so the spawns are correct. However, maybe your base is near a village? I should maybe reduce the range check for villages.

**Comment by IdrisQe** [comment]
My base being "near" a village is debatable depending on definition of near, but I'll see if this fixes it!

If not then... Maybe I have a mod or something which is somehow marking any structure with a bed and possible profession blocks as a village or something weird. Not that I'm complaining, the rats are cute!


Also, I'm not sure if this is meant to be this way so I feel like opening a seperate issue would be a bit silly, but when Rats are sitting, are they supposed to eventually stop the sitting animation and resume their standing/idle animations? They still act as sitting, staying in place and not following, and right clicking them again puts them back in "sitting" sitting. If this is intentional... I like it! Gives them more life, rather than just remaining flat (as cute as it is) forever. Though this may be another mod acting weird too, no idea! The problem with big modpacks...

...Also also, not sure if you're taking requests but I thought of something silly to add for a named rat:
Either "Dire Rat" or "Rodent of Unusual Size" leading to the rat being 2x its normal size but with nothing else changed. Big bois!

**Comment by doctor4t** [comment]
I know sitting rats and relogging will show rats as not sitting, so that may be your issue.

For the dire rats, I have that planned, I just cannot say when it's gonna come out. They would be large rats  you could also use to transport stuff and ride.

**Comment by IdrisQe** [comment]
...I was just talking about a funny nametag thing but actually I much prefer that idea!
Riding a rat into rattle - er battle- would be amazing!
