### ISSUE TITLE
Rats not spawning (1.19.2)

### ISSUE THREAD

**Issue by enzomtpYT** [Ladysnake/Rats-Mischief#103]
Hello ! I'm having a technical difficulty with rats spawning, im on quilt 1.19.2, i have QFAPI installed, GeckoLib & Rat's Mischeif.

i went to a village, killed all villagers with the /kill command, and waited 10 minutes, i then tried to tp to a rat using `@e[type=ratsmischief:rat,limit=1]`

![image](https://user-images.githubusercontent.com/40535918/220149825-6e129e62-8e52-4789-a9bc-550ed036e13b.png)

**Comment by enzomtpYT** [comment]
Also tried on fabric, with fabric api, gecko lib and rat's mischeif but same result !

**Comment by enzomtpYT** [comment]
Ok, my bad, i just had to wait 30min in the village . . .

**Comment by noname9312** [comment]
Why is it closed?  i have the same issue
