### ISSUE TITLE
only wild rats are spawning no other rats are

### ISSUE THREAD

**Issue by madjackmatt** [Ladysnake/Rats-Mischief#107]
olny wild and gold i spawned 1000 of them and 5 gold the rest are wild rats

**Comment by Xiribidus** [comment]
You have already been told this is intended behavior, read the [wiki](https://ladysnake.org/wiki/rats-mischief#pet-rat-types) for more info about pet rat skins

**Comment by madjackmatt** [comment]
no the wiki says that 1 in 150 are gold and wild rats

**Comment by madjackmatt** [comment]
i have not goten any other rats in over 3k+ rats

**Comment by Xiribidus** [comment]
1 in 150 rats are gold rats, the rest wild rats, that's what the wiki says

**Comment by madjackmatt** [comment]
yes, but i tink its overkill i have spawn over 3000 rats and 5 where gold and the rest are wild

**Comment by Xiribidus** [comment]
All rats spawning naturally are supposed to be wild rats. If you breed 2 wild rats the rat baby will have a random pet rat skin.
Golden rats are supposed to be a rare artifact, that's why they have a low chance of spawning as well.

**Comment by madjackmatt** [comment]
i was useing a command block does that count as a rat spawning naturally?

**Comment by Xiribidus** [comment]
Yes

**Comment by madjackmatt** [comment]
ok, thank you, i will try with breeding them if that doesn't work ill open a new issue

**Comment by Pyrofab** [comment]
Please do not spam issues. I am closing this one, but you can re-open it if your problem hasn't been resolved.
