### ISSUE TITLE
Rat Kid Breeding Makes Unnamed Rat Kids

### ISSUE THREAD

**Issue by ChaosDogG** [Ladysnake/Rats-Mischief#108]
Not entirely sure if this is remedy-able due to how the Rat Kid is handled, but when I (have my rats) breed Rat Kids, their offspring are more than likely unnamed Rat Kids. Perhaps as a way to hide it better, when they breed, if the child happens to be a Rat Kid, they have the corresponding name upon spawning. 'Tis not anything game-breaking, just a lil more on the nitpick-y side.

**Comment by doctor4t** [comment]
Works as intentional
