### ISSUE TITLE
Crash on 1.19.4 because of no geckolib, yet geckolib is installed.

### ISSUE THREAD

**Issue by GavinGoGaming** [Ladysnake/Rats-Mischief#111]
Im using Geckolib-Quilt-1.19.4-4.2
but get this:

Rat's Mischief requires version [3.1.0, ∞) of geckolib3, which is missing!
- <mods>/ratsmischief-1.4.0.jar

(quilt server)

**Comment by Xiribidus** [comment]
Rat's Mischief 1.4 is for mc versions 1.19-1.19.2!
1.19.3 and 1.19.4 are 2 versions that both need separate ports most of the time, such ports do not exist at the moment.
