### ISSUE TITLE
Can't combine curse of the rat book with Rat Master Armor using Enchancement mod

### ISSUE THREAD

**Issue by Shulej** [Ladysnake/RATs-Mischief#114]
When I try to combine normal Rat Master Armor parts with a Curse of the Rat book, the new enchanted part just has the glow and no curse of the rat enchantment showing. Trying to combine already enchanted Rat Master Armor parts with the curse of the rat book fails. I tried removing the Enchancement mod and it works now.

**Comment by slothshoe** [comment]
Enchancement only lets you add one enchant to items. Curse of the rat has to enabled in the Enchancement config with the id ratsmischief:rat_curse.

**Comment by Shulej** [comment]
I see. I watched Rat's video and he combined the enchants so I thought he changed something and it stopped working. Thank you very much for your answer! You can close this issue now :P
