### ISSUE TITLE
Rats can only spawn on y-level of player

### ISSUE THREAD

**Issue by TheGreatCatAdorer** [Ladysnake/Rats-Mischief#13]
https://github.com/Ladysnake/Rats-Mischief/blob/main/src/main/java/ladysnake/ratsmischief/common/world/RatSpawner.java

Spawning is done at an offset of (i, 0, j) from the player, where i and j are random from 8 to 32.  While this may seek to replicate vanilla pack spawning, it causes rats to only be able to spawn on a plane, leading to odd survival behavior and inconsistency with vanilla.

**Comment by doctor4t** [comment]
I want rats to spawn when a player walks inside a village, so I'm not sure how this is an issue?
Besides, what do you mean by "leading to odd survival behavior and inconsistency with vanilla"? I for one never had any issue with the rat spawns when playing in survival. And how is it inconsistent with Vanilla when cat spawn coordinates in villages are calculated the same way?
