### ISSUE TITLE
are quilt clients via curseforge bad for this?

### ISSUE THREAD

**Issue by CozyDub** [Ladysnake/RATs-Mischief#138]
I have this mod installed on a quilt client (via setting up a new mod profile on curseforge with quilt selected) and mischief keeps saying I don't have geckolib installed, although I do, and I can't open the game. I'm assuming this is an issue with using curseforge, but I'm not very good at troubleshooting so I figured I'd just ask here

also, I may be stupid so consider that too

**Comment by avetharun** [comment]
Make sure you are using the correct geckolib version

**Comment by CozyDub** [comment]
I am

**Comment by UpcraftLP** [comment]
Can you post the exact error message, along with a screenshot of your mods folder?

**Comment by CozyDub** [comment]
![java_GWzcMgBAhL](https://github.com/Ladysnake/RATs-Mischief/assets/154031383/d1ac188b-a03f-47a7-91ea-b403ae1ae732)
![explorer_TP5d0KPiDY](https://github.com/Ladysnake/RATs-Mischief/assets/154031383/12a8e12a-fbbc-4432-9b23-89b00b03e4de)

**Comment by UpcraftLP** [comment]
You have geckolib 4, not 3.

Also RAT's Mischief is only updated to MC1.19.2 and will not work with newer versions of Minecraft.

**Comment by CozyDub** [comment]
heck
