### ISSUE TITLE
Rats change colour, apparently

### ISSUE THREAD

**Issue by IdrisQe** [Ladysnake/Rats-Mischief#14]
So... The other night I was playing my world, and noticed my rat was albino...
Now I'm absolutely sure the rat I tamed when I started this world was _not_ albino, but i figured maybe I just misremembered.
Today, when I loaded the world... It was not albino. Again, I didn't think much of it, but after returning from a mining trip, the exact same rat was standing and albino again.

I reloaded the world, and the rat was light brown (and standing again, but I sat him back down)
![2021-03-10_16 50 31](https://user-images.githubusercontent.com/40530630/110720794-0ad16400-81c4-11eb-9c63-918e4a6e6d16.png)

And on a hunch, I went far away so the chunks unloaded, then came back.
The rat was standing again... (Still the same rat! I only tamed one in this world, and he was still in the same place with the sitting behaviour!) and was now grey.
![2021-03-10_16 53 34](https://user-images.githubusercontent.com/40530630/110720876-33595e00-81c4-11eb-8deb-2dc9ea6700d1.png)

I left the area once more, to ensure I wasn't seeing things (I hadn't checked my screenshots yet)
and sure enough, when I came back, the rat was now dark brown, for some reason.
![2021-03-10_16 58 43](https://user-images.githubusercontent.com/40530630/110720939-4f5cff80-81c4-11eb-9f2b-5f0b39720646.png)

I reloaded the world again and he was grey again, but I didn't screenshot since I think the point is made. Tried searching my log but there wasn't anything about rat textures so I have no idea why the textures seem to be changing every time I reload. Is it because he isn't named, maybe? I have no idea.

**Comment by doctor4t** [comment]
Do you have Immersive portals?

**Comment by IdrisQe** [comment]
...Oh.
I do, are they incompatible?

**Comment by doctor4t** [comment]
Yes, a previous issue was opened for this.

**Comment by qouteall** [comment]
I wanted to test it by `modImplementation ('com.github.Ladysnake:Rats-Mischief:1.0.3')` but gradle gives `Could not resolve com.github.Ladysnake:Rats-Mischief:1.0.3@net.fabricmc.yarn.1_16_5.1.16.5+build.1-v2.
`

**Comment by qouteall** [comment]
I suspect that it's a networking issue. Why does RatEntity use custom spawn packet? https://github.com/Ladysnake/Rats-Mischief/blob/main/src/main/java/ladysnake/ratsmischief/common/entity/RatEntity.java#L213
LivingEntity's default createSpawnPacket implementation should be sufficient.

**Comment by qouteall** [comment]
Probably fixed in IP 0.84 https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v0.84-1.16

**Comment by doctor4t** [comment]
> LivingEntity's default createSpawnPacket implementation should be sufficient.
Yes it should. I just made a custom packet implementation cause that's how I always do, most of my entities never being living entities and therefore requiring custom packets. I'll test without my custom packets, but nice if you managed to fix it!

**Comment by IdrisQe** [comment]
The IP fix does seem to have fixed it! Interestingly, installing the new version seems to have re-tamed my rat! Which means I guess the data wasn't getting deleted but instead just... not used? Not sure! But it's working now!
