### ISSUE TITLE
half the items are gone

### ISSUE THREAD

**Issue by thelostdragon** [Ladysnake/RATs-Mischief#145]
as it says in the title half of the items are gone such as the armor and mask, the ocarina, spy rats and clothed ingots i downloaded the mod from modrinth for 1.19.2

**Comment by Xiribidus** [comment]
What version did you download?

**Comment by thelostdragon** [comment]
it says i have 1.40 for the mod

**Comment by UpcraftLP** [comment]
> it says i have 1.40 for the mod

that's your issue then, you want v2.0 or later

**Comment by thelostdragon** [comment]
ok thank you for the info im going to go fix that

**Comment by thelostdragon** [comment]
is the 2.0 update only available for quilt?

**Comment by UpcraftLP** [comment]
that is correct

**Comment by Pyrofab** [comment]
Note however that the vast majority of fabric mods work on quilt with no issue, so you should be able to migrate by just switching your loader and API

**Comment by thelostdragon** [comment]
good to know many thanks
