### ISSUE TITLE
can you please update to 1.20.1

### ISSUE THREAD

**Issue by Thinkseal** [Ladysnake/RATs-Mischief#148]

**Comment by hatkidchan** [comment]
> closed as **completed**

![image](https://github.com/Ladysnake/RATs-Mischief/assets/35804000/8bc2fa8f-a545-403d-bc14-5f41f15d2df0)
![image](https://github.com/Ladysnake/RATs-Mischief/assets/35804000/4c288dbb-92b5-46ae-9245-5370b59e66a3)

or is it?

**Comment by hatkidchan** [comment]
#134 is related to that, would be nicer if it was at least clear that it's a duplicate
