### ISSUE TITLE
Instantaneous Crashing

### ISSUE THREAD

**Issue by 13utterflyeffect** [Ladysnake/RATs-Mischief#149]
I've been trying to create a modpack to mess with mods on Modrinth, but I've isolated some kind of issue with this mod, which I'm sad about because I was excited to play it. It's not an incompatibility or something to do with GeckoLib, it's just this mod specifically. It breaks before even starting.

I am definitely new to Modrinth and Quilt, but I don't think I did anything to cause this. I think this is all the relevant information? I removed some info just because it was about my PC and I was a little worried I'd accidentally share something private but if needed i can add other parts to elaborate on the issue since it's possible i deleted something important since I'm not code-savvy at all. 

[ratsmischiefcrash.txt](https://github.com/Ladysnake/RATs-Mischief/files/14470813/ratsmischiefcrash.txt)

**Comment by Eddykids68** [comment]
I'm having the same exact issue down to the crash message and it's really depressing honestly. I really want to play with the rat mod :[
I am also new to both modrinth and quilt, being solely a forge user before this. I even tried installing some kind of quilted fabric api mod and it did nothing. Very bummers, hopefully we can have help on this

**Comment by XAlaskan420X** [comment]
Hey I think I have the same error. At the bottom it says error code -1. I don't know what that means also the CPU is unknown. Is that causing the crash?

**Comment by LegendaryLogan1** [comment]
I have the same issue, but I have no idea why its even happening. I tore down my entire mod pack and only found it after deleting all the other mods...

**Comment by UpcraftLP** [comment]
Going off the original crash log: you need to downgrade QFAPI to [this exact version](https://modrinth.com/mod/qsl/version/4.0.0-beta.30+0.76.0-1.19.2).
