### ISSUE TITLE
staff config - enhancement

### ISSUE THREAD

**Issue by superon** [Ladysnake/Rats-Mischief#15]
could you would you add a config so we can chose to have rats not drop the various staffs?

**Comment by doctor4t** [comment]
But then how would you get them? I'm not sure I understand, you just don't want people to be able to use staffs?

**Comment by superon** [comment]
yea that's my thinking :) don't know if i'd not want to use any particular staff (well maybe the breeding one) but stil others might.

**Comment by doctor4t** [comment]
I'm not really sure I understand... You want a client side option that says rats don't drop staff specifically for you?

**Comment by superon** [comment]
that would be good too, i was thinking more along the lines of being able to not have the staffs included in play at all..
if there could be an option to have them also only drop them for players that have attained a specific advancement too though ... sounds awesome
