### ISSUE TITLE
RAT's Mischief instantly crashing for an unknown reason.

### ISSUE THREAD

**Issue by Bball262** [Ladysnake/RATs-Mischief#150]
Whenever I try and launch RAT's Mischief with any version of quilt using one of the RAT's Mischief versions from 2.0.0+ It will crash giving me this error message: 

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'quilted_fabric_renderer_indigo'!

Before you ask, I have tried installing Indigo, but instead it just returns the same thing but instead provided by "indigo"
Any fixes?

**Comment by UpcraftLP** [comment]
downgrade QFAPI a few versions.
