### ISSUE TITLE
Error code 1 trying to launch game

### ISSUE THREAD

**Issue by PaganGoose** [Ladysnake/RATs-Mischief#152]
Every time I try to launch my game(I only have this, gecko and QFAPI installed) it just shows an error. I'm launching it from curse forge. I've also tried using other versions of QFAPI
![image](https://github.com/Ladysnake/RATs-Mischief/assets/171743227/1cd468ab-f963-4e66-a4a8-47a0803c7015)

**Comment by Xiribidus** [comment]
next time post the latest.log or crash report file [please].

anyway: you need to downgrade QFAPI to this exact version: https://modrinth.com/mod/qsl/version/4.0.0-beta.30+0.76.0-1.19.2

- Up, 30/04/2024

**Comment by Xiribidus** [comment]
Might also be missing trinkets but curseforge should add that automatically I would think

**Comment by PaganGoose** [comment]
thank you
