### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by 12Fate12** [Ladysnake/RATs-Mischief#157]
[crash-2024-08-29_17.23.41-client.txt](https://github.com/user-attachments/files/16800656/crash-2024-08-29_17.23.41-client.txt)

**Comment by Xiribidus** [comment]
Could you test if this happens with just Mischief (+dependencies ofc)?

**Comment by 12Fate12** [comment]
oh i doesn't do i have to go through all of them to figure it out

**Comment by 12Fate12** [comment]
i mean  all of the mods

**Comment by 12Fate12** [comment]
oh i fixed it thanks for the help
