### ISSUE TITLE
Suggestion: Easy Potion Application

### ISSUE THREAD

**Issue by IdrisQe** [Ladysnake/Rats-Mischief#17]
So I was watching the devstream on youtube and thought of how much of a pain it'll be to get all your rats in one spot to hit with splash or lingering potions... But then I came up with a couple ideas for how to mitigate that if you want to buff your rats easier when this update comes out!

1. Rat Mask Propogation: Similar to how enchantments propogate, it makes any Rats owned by you recieve any potion effects (positive or negative, so there's a downside too so it isn't too powerful!) for 1/2 the time it applies to you (unless they already have a source of the effect) This could still be too powerful and quick-to-apply to consider (though my understanding is that the Rat Mask will be very difficult to acquire anyway)
2. Pouch Pouring: Holding a Rat Pouch in your offhand while using a potion in your left will give the effect (for 1/2 duration) to all your rats as well as yourself, basically splitting the effect between yourself and your rats, where you can then release them and the effect timer will start to go down. Wanna buff your rats? Quickly retrieve them and drink a potion, then let them back out!

**Comment by doctor4t** [comment]
I already mentioned the potion rat mask idea during a dev livestream but the pouch pouring idea sounds nice. Although I'll most likely make the effect only go to the rats in the pouch and not the player.
