### ISSUE TITLE
rat finished my eternal steak :(

### ISSUE THREAD

**Issue by superon** [Ladysnake/Rats-Mischief#20]
after i clicked a rat to tame it..
also in testing i found a hurt rat (tamed) will eat one off the ground, sometime it'll simply vanish without healing the rat (or eating animation) and sometimes it'll behave as i'd expect, rat (eats and brings steak back to me after eating animation) gets healed.
seems to be the same with wild rats, sometimes the steak simply vanishes..
ratsmischief-1.0.4
artifacts-3.0.3+fabric

**Comment by doctor4t** [comment]
I can't seem to be able to reproduce this bug. On the latest version of Artifacts and Mischief, I've tried extensively and the eternal steak is never consumed.
