### ISSUE TITLE
Request: Turn off/on 'Saturation converts to Regeneration' feature

### ISSUE THREAD

**Issue by Buffoony** [Ladysnake/Rats-Mischief#24]
The title explains it pretty well.

**Comment by doctor4t** [comment]
Yes but it doesn't explain the reason.

**Comment by Buffoony** [comment]
My bad. It causes incompatibilities with mods that add effects to randomly selected mobs as modifiers. [Eldritch Mobs](https://www.curseforge.com/minecraft/mc-mods/eldritch-mobs) being a prime example.

**Comment by doctor4t** [comment]
How so exactly?

The reason behind this is actually for consistency, so when they eat an item that offers saturation and no actual food, it actually heals them like a food item would (given that food items heal rats at 1:1 foodpoint:healthpoint rate).

**Comment by Buffoony** [comment]
The game crashes if you have Eldritch Mobs and the latest version of Rat's Mischief. The most probable thing that could cause this would be the Saturation thingy, as nothing else would make the mods "overlap".

**Comment by doctor4t** [comment]
???????? Then just post the crash and open an issue "Crash with Eldritch mobs". There's explicit compat with Eldritch Mobs, so maybe it's that that crashes.

Try and avoid making assumptions, it won't help fix the problem and will just make everyone lose time. If X is your problem and you think Y will fix it, don't ask for Y, but explain X.
