### ISSUE TITLE
[Suggestion] Improved Rats Vs. Cat & Rat Training

### ISSUE THREAD

**Issue by SaltSouls** [Ladysnake/Rats-Mischief#32]
This is going to start with, **no I don't want you to just make your mod like Rats**. I like the behaviors and what not of this mod far more than the forge Rats mod(They act too much like robots), so I would like to suggest features like this be implemented with more of that natural animal kind of feeling that this mod provides. I will break this down to make it slightly more comprehensible.

### RAT VS. CAT

I think this one should be pretty simple and shouldn't need much explanation. While I like the idea that rats will fight back, cats are **still** the predators to rats and mice. Therefore the fact that a single rat can scare off a cat and will even so boldly **fight** it, seems very unrealistic to their natural behaviors. Firstly, cats should be able to fight back. I feel it would make sense as a single rat probably doesn't actually put up much of a fight against a cat, while multiple could possibly take one down. Secondly, cats should scare away rats, unless the rats are in a group of 5+, in which the behavior that is currently in place will take effect. This one would make it seem more realistic and also kind of comical to see a cat being chased around be a swarm of rats.

### RAT TRAINING

This one is probably one that someone is going to comment saying "iT's N0t SUppOsEd tO ALloW FoR EAsY AuT0MaTioN". To which is say, this is a suggestion and nothing more. The idea behind rat training comes from the idea that most scientists use when creating experiments for rats/other living creatures. Teach a rat to do something over a long period of time, and eventually it will start to do so without you having to tell it to anymore. These things almost become second nature to the rat. I want to take this mentality/characteristic and apply it to the rats in this mod.

What do I mean by this? I mean that you could teach a group of rats to harvest your crops automatically without you having to be there or holding the staff anymore. This would not be an instantaneous process though, rather it would take some time in order to actually get the rats to do so without your intervention. The training would consist of being around the rats you want trained and using the already implemented staves in order to tell them what job to do.Thus the training acts as more of an addition to the current method rather than a replacement. The one thing I would like to add would be that this method wouldn't be flawless automation either. I would like to think of it as natural automation, where there is a chance that even the trained rat will just decide, no I don't want to do this, and not do the job. Essentially the longer you train the rat to do a job, the more likely it is to do the job with an upper limit of 85% chance of doing it, that way they don't feel robotic. Though rats will still always do the work if you are using the staves to command them. You could also make it so that rats can only be trained to do one job at a time, meaning that if you start training a rat to do a different job, they will lose the experience they have in their current job in favor of the new one. This prevents the rats from being too overpowered as you would need quite a lot of them to properly automate anything.

This feature will allow players to have rats that are specialized to do certain jobs without making the rats seem like they are just robotic golems that mindlessly obey every command. It adds more versatility to the mod and what it can do without taking some of the fun of actually having to command the rats to do said things while lording over them like a mad scientist. I feel like this system could also be applied to any future careers that the mod may add, as if implemented properly, it would just be a stat that the rats have that ticks up over time as the player trains them to do said job. I would get into more jobs and careers for the rats, but that if for another suggestion and just as much I don't know what is currently planned for the mod, so I would rather not go prattling on about features that may already be in the works. In summary for this section, funny rat do job without player holding silly command stick.

**Comment by doctor4t** [comment]
> cats are still the predators to rats and mice
Mice only, most cats are afraid of rats. If you have a rat problem, you use dogs. There are multiple videos of a rat chasing a cat online, and from my personal experience, my pet rats used to chase my cats in order to play with them, hence why the behavior is currently how it is, and I don't plan to change as of now.

As for the training suggestions, while I like the idea of it, I think it might add too much unpredictability and cause more issues than good. The command system is not perfect as it is, and I'm planning to work further on it in the future, but right now, my plans are elsewhere.

**Comment by Xiribidus** [comment]
"Cats are still the predators to rats and mice. Therefore the fact that a single rat can scare off a cat and will even so boldly fight it, seems very unrealistic to their natural behaviors." Cats are actually scared of rats, I even saw a cat fleeing two guinea-pigs... So while it may not clash with the real world it just clashes with expectations (also rats don't actually harm cats anymore). Still a fun idea imo.
I think the training could backfire since the rats might start doing things that you don't want them to do, like harvest-trained rats suddenly destroying your decorational fields. In addition to that I also can't rly imagine how you would train rats with the collection staff and the love staff since the collection staff needs certain materials nearby and has a lot of different uses and the love staff requires you to drop certain food items on the floor, and while that could be automated by droppers the rats would then just end up as machines again.
Just my opinion though but those are the problems that come to my head with this, even though I like the ideas.

**Comment by SaltSouls** [comment]
> I think the training could backfire since the rats might start doing things that you don't want them to do, like harvest-trained rats suddenly destroying your decorational fields. In addition to that I also can't rly imagine how you would train rats with the collection staff and the love staff since the collection staff needs certain materials nearby and has a lot of different uses and the love staff requires you to drop certain food items on the floor, and while that could be automated by droppers the rats would then just end up as machines again.

I would say that the collection staff might be the one exception to the training system as it would likely be too destructive to allow rats to do automatically. Though the other ones can have some simple solutions without making them machine like. The rat nest is a currently planned feature that I think would solve a lot of the problems presented. ![RatNest.bmp](https://user-images.githubusercontent.com/36361103/124807504-abd1f080-df12-11eb-8331-96b65faa56e2.png)
It would allow rats to do a job within a radius around the nest and then return to the nest and storing item there. The items could then be either pulled out automatically with a hopper or manually by the player. for lets say the love staff/other future staves that might require items to work, there could be a new storage block added(or it can just use the vanilla ones) to allow the rats to pull the items out of it and use it for the job that they were trained to do. It could even be that the rat nests could be used as the storage for this very thing, allowing player to both take items out as well as putting items in for the rats to use. This could work for breeding rats allowing them to pull out the required item for the animal they are breeding, though you can make it so they don't always grab the correct one if you are trying to breed multiple animals. It could also work for, lets say, guard rats where they could go back to their nest after defending the area around them and eat whatever food is currently there. To reiterate, this system would both prevent rats from following you and doing jobs you didn't want them to do, as well as allowing you to limit the area in which a job can be done as well as providing the resources in which to do said job.

> As for the training suggestions, while I like the idea of it, I think it might add too much unpredictability and cause more issues than good. The command system is not perfect as it is, and I'm planning to work further on it in the future, but right now, my plans are elsewhere.

As A side note, I would say that you could even forgo the training element and just allow the player to link/place a rat staff with a rat nest, thus telling the rats of that nest to do this job when available. Each nest can only have one staff attached to it, again preventing the rats from being able to do multiple jobs, making them more specialized in what they can do. This would prevent the entire training mechanic from having to be implemented and instead would just use the already existing mechanics of the rat staves in order to achieve the goal I'm thinking of. I figure a way of getting the staves into the nest can be done with a similar method to that of the rat pouches, which is just a simple shift+right click with them in your hand. Again, this allowing for the entire training mechanics to be thrown out in favor of giving entire nests jobs that they can do by attaching one of the various staves to it.

**Comment by doctor4t** [comment]
Keep in mind that the rat nests will not be implemented to facilitate full automatisation. By design, I wish to keep an intervention from the player in order to execute the more specific tasks.
