### ISSUE TITLE
1.17 Recipe Conflict

### ISSUE THREAD

**Issue by hazard975** [Ladysnake/Rats-Mischief#34]
The Leather Rat Pouch has the same crafting recipe as bundles in 1.17.

**Comment by hazard975** [comment]
Added a pull request to fix this issue

**Comment by doctor4t** [comment]
Aren't bundles made from rabbit hide and not leather? Besides, the craft is currently disabled, so how would it conflict?

**Comment by hazard975** [comment]
![image](https://user-images.githubusercontent.com/61721756/125317256-d9e67480-e306-11eb-9d83-a70ed0bc8c74.png)
![image](https://user-images.githubusercontent.com/61721756/125317390-f84c7000-e306-11eb-81df-1fda7b06b772.png)
Seems like they are not disabled to me.

**Comment by doctor4t** [comment]
Then you definitely have a mod that alters this behaviour...

![image](https://user-images.githubusercontent.com/25477005/125317878-a07b2c80-e339-11eb-8c4e-524584394dfc.png)

**Comment by doctor4t** [comment]
No more details, closing this
