### ISSUE TITLE
Rats spawn everywhere

### ISSUE THREAD

**Issue by d4rkm0nkey** [Ladysnake/Rats-Mischief#36]
I made a mod pack that includes Rat's Mieschief and rats are spawning everywhere. The whole spawn area is full of them already.
We spawned on islands and they just seem to spawn there as well.
It's a rat plague and we don't know what to do.

It is in Minecraft 1.16.5

Here are the mods:
    Simple Voice Chat (by henkelmax)
    BetterNether (by paulevs)
    BCLib (by paulevs)
    Tool Stats (by DarkhaxDev)
    Krypton (by tuxed)
    Notes Fabric (by reeve567)
    Untitled Duck Mod (Fabric) (by Paspartout)
    Chat Heads (by dzwdz)
    Fast Leaves (by Flytre7)
    Phosphor (Fabric) (by jellysquid3)
    Lithium (Fabric) (by jellysquid3)
    Mo' Structures (Fabric) (by ffrannny)
    Damage Tilt (by Charles445)
    The Parakeet Mod (by javidg96)
    [FABRIC] Monster Of The Ocean Depths (by dinohunter0727)
    ToroHealth Damage Indicators (by ToroCraft)
    Better Biome Blend (by FionaTheMortal)
    MAmbience (by andre111_)
    MaLiLib (by masady)
    Rat's Mischief 🐀 (by doctor4t) 1.1.2
    CleanCut (by Rongmario)
    No Angled Brackets (by Flytre7)
    Mod Menu (by ProspectorDev)
    MobZ (by Globox_Z)
    Pling (by haykam)
    No Recipe Book (Fabric) (by Gray_ray)
    Wildfire's Female Gender Mod (Fabric) (by WildfireRomeo)
    VoxelMap (by MamiyaOtaru)
    Chicken Drop Feathers (by baithoven21)
    Home Camp (by The_Fireplace)
    LazyDFU (by tuxed)
    Dynamic FPS (by juliand665)
    Alaska Native Craft (by whangd00dle)
    Cloth API (Fabric) (by shedaniel)
    Door(s) Coupling [FABRIC] (by Zero_DSRS_VX)
    Fabric Language Kotlin (by modmuss50)
    Traverse (by ProspectorDev)
    LambDynamicLights (by LambdAurora)
    Color Unchained (by Draylar1)
    EditSign (Forge&Fabric) (by RakSrinaNa)
    Enchantment Lore (by muteone2)
    RandomPatches (Fabric) (by TheRandomLabs)
    Smooth Boot (Fabric) (by UltimateBoomer)
    Anvil Fix (by UpcraftLP)
    Stoneholm, Underground Villages (Fabric) (by TheGrimsey)
    Fabric API (by modmuss50) 0.36.0+1.16
    Direbats (Fabric/Quilt) (by andantet)
    Dynamic Music (by LudoCrypt)
    Charm (by svenhjol)
    Architectury API (Fabric) (by shedaniel)
    Villager Names (Fabric) (by YumatanGames)
    BetterEnd (by paulevs)
    Lapis Reserve (by sfort__)
    Falling Leaves (Fabric) (by RandomMcSomethin)
    Item Scroller (by masady)
    Enchantment Descriptions (by DarkhaxDev)
    Monsters in the Closet (by Jakob_Zabek)
    FerriteCore (Fabric) (by malte0811)
    Dark Loading Screen (by Neecko5b84)
    Roughly Enough Resources (by theorbagain)
    Cave Biomes (by SuperCoder79)
    Repurposed Structures (Fabric) (by telepathicgrunt)
    Ok Zoomer (by EnnuiLangeweile)
    Unlit Campfire (by thecech12)
    EasierVillagerTrading (by Giselbaer)
    Oh, How the Crafting Has Tabled! (by P3NG00)
    Fabric Waystones (by LordDeatHunter)
    Faster Minecarts (by neondrp)
    Here be no Dragons! (by kb1000)
    Entity Culling Fabric/Forge (by tr9zw)
    Dual Riders (by Flytre7)
    GeckoLib [FABRIC] (by ThanosGecko)
    Stay True (by backto4myula)
    Roughly Enough Items Fabric (REI) (by shedaniel)
    Gilded Netherite (by Azriel_Taylor)
    Item Model Fix (Fabric) (by Pepper_Bell)
    Iris Shaders (by coderbot)
    Cloth Config API (Fabric) (by shedaniel)
    Better Dropped Items (by Draylar1)
    The Veggie Way [FABRIC] (by kwpugh)
    Seamless Loading Screen (by Jakob_Zabek)
    Horse Stats Vanilla (Fabric) (by TeaJ4y)
    Illuminations 🔥 (by doctor4t)
    Cull Leaves (by Motschen)
    ToolTipFix (by Kyrptonaught)
    Charmonium (by svenhjol)
    Adorn (by Juicebus)
    'Slight' Gui Modifications (by shedaniel)
    William Wythers' Overhauled Overworld (by cristelknight)
    Dynamic Sound Filters (by andre111_)
    Mo'Enchantments (by biom4st3r1)
    AdventureZ (by Globox_Z)
    Talking Villagers (by TeaJ4y)
    Compostable Rotten Flesh (Fabric) (by TeaJ4y)
    More Structures add-on for William Wythers' Overhauled Overworld (by cristelknight)

**Comment by doctor4t** [comment]
I don't see any issues with this. Closing it.

Jokes aside, yes it's been a long running bug, if there are beds and workstations and no villagers it gets counted as an empty village, no matter if it's actually close to a generated village or not. It's fixed in the latest version for Mischief, although that is on 1.17. Maybe you'd like a fix for 1.16?

**Comment by d4rkm0nkey** [comment]
A fix for 1.16.5 would be awesome as a lot of mod packs can't be updated to 1.17 right now.
Yeah, it was kinda cool, having a rat plague on some Islands, but it started to annoy the people on my server that rats were everywhere they build something.

Thanks for the fix.

**Comment by doctor4t** [comment]
I love my Minecraft rats, but even for me they started getting on my nerves after the first week when playing and having them spawn everywhere.

Alright I'll fix it for 1.16, should be easy enough.
