### ISSUE TITLE
Rats are pigs

### ISSUE THREAD

**Issue by AceSkym** [Ladysnake/Rats-Mischief#37]
Currently in my game the rats are all showing up as pigs. They show up named "entity.ratsmischief.rat" 

I tried to find a config but I'm unable to find a config, I'm currently running the mod on a private fabric 1.17 server.

**Comment by doctor4t** [comment]
What the hell. Could you maybe provide more information? Like screenshots, server logs and client logs.

**Comment by Pyrofab** [comment]
Are you sure Rats' Mischief is currently installed ?

**Comment by AceSkym** [comment]
Yes, I'm able to tame them as normal (tamed the one in the screenshot with bread for example). I have multiple other mods on the server installed, so I've also attached my latest log. I couldn't get screenshot to work on my computer for whatever reason so I had to take a picture of my screen instead. Additionally the Rat pigs do attack mobs as the rats are supposed to behave. I'm not sure if it's a mod conflict or what's gone on. 

[latest.log](https://github.com/Ladysnake/Rats-Mischief/files/6819174/latest.log)
![20210714_180721](https://user-images.githubusercontent.com/63478761/125699928-e9eac2d2-8b76-491a-9b03-a637aec1c09c.jpg)

**Comment by AceSkym** [comment]
Additionally, here are the mods on the server. 

![image](https://user-images.githubusercontent.com/63478761/125702224-c88c3eb0-0fa6-4d00-b353-9fa6606a0901.png)
![image](https://user-images.githubusercontent.com/63478761/125702302-7b8a749b-702f-446c-8d73-0024179af51c.png)
![image](https://user-images.githubusercontent.com/63478761/125702322-fc8c3757-1d35-48dc-ad95-2882b977af98.png)

**Comment by AceSkym** [comment]
Update: I started a new world to make sure no other mods that had been removed were still working, I went and found a new village, killed off the villagers and waited for rats to spawn. They still spawned in as pigs with the same name. Here's the log to that world. 
[latest (2).log](https://github.com/Ladysnake/Rats-Mischief/files/6819405/latest.2.log)

**Comment by doctor4t** [comment]
What Fab asked was if you have Mischief both on the client and the server. You've proven you have it on the server, but is it present on the client?

I only see this as a possible explanation, given the rats behave properly according to your claims, only that their render isn't correct.

**Comment by AceSkym** [comment]
Ah, I see. I didn't see that this needs to be client and server. I didn't see that listed on the Wiki or the page. I currently only have it installed on the server, not the client.

**Comment by Xiribidus** [comment]
You usually need mods on the client as well, that's why it isn't specifically stated in the wiki.

**Comment by AceSkym** [comment]
The majority of the mods I'm running are not needed on the client side, with few exceptions. Which is why I didn't know.

**Comment by doctor4t** [comment]
> 
> 
> The majority of the mods I'm running are not needed on the client side, with few exceptions. Which is why I didn't know.

No worries there! I'm still surprised you managed to connect to the server without Mischief on the client though haha.

For the future, keep in mind that mods that add textures / models / new visuals to the game in general will require the mod to be installed on the client! Hope you can enjoy the rats now that they're back to their normal ;)
