### ISSUE TITLE
Broken textures on special rats with elytras, it happens to everyone except remy

### ISSUE THREAD

**Issue by DavidPipo** [Ladysnake/Rats-Mischief#62]
![2021-12-12_03 35 35](https://user-images.githubusercontent.com/88998499/145703008-f75f099e-ebad-41bc-b258-08b63663c8cd.png)
![2021-12-12_03 35 37](https://user-images.githubusercontent.com/88998499/145703013-f908a8da-b20f-4d39-9f5e-4c4c7ec1afd0.png)

**Comment by MoriyaShiine** [comment]
https://github.com/Ladysnake/Rats-Mischief/commit/1286afbc447516da2bd2426a8da32eb3d9e9fb0a
