### ISSUE TITLE
All the rats are brown except for babies.

### ISSUE THREAD

**Issue by RagnarokOroboros** [Ladysnake/Rats-Mischief#63]
Golden rats can still spawn though.
![image](https://user-images.githubusercontent.com/96100749/145935345-3b2dbc18-303e-4a56-97b9-e45d8e8e1b0a.png)
![image](https://user-images.githubusercontent.com/96100749/145935359-1644c684-3c4e-4e70-8e61-71185e5278da.png)
![image](https://user-images.githubusercontent.com/96100749/145935370-4c7cc963-ba97-4051-a9f3-bcff5c58e9cc.png)

**Comment by doctor4t** [comment]
Working as intended, only wild rats spawn in the wild. Fancy rats need to be obtained through breeding.
