### ISSUE TITLE
says i need geckolib when i HAVE geckolib

### ISSUE THREAD

**Issue by Cedesect** [Ladysnake/Rats-Mischief#67]
my geckolib is up to date, same version as my loader and fabric and rats mischief and all of it, but it says that this mod cant load because I dont have geckolib??? please help i have 3 braincells and im not smart enough to know how to fix this

**Comment by SuperGamingBros4** [comment]
I had the same issue, just make sure that the filename of GeckoLib has _fabric_ in it. Otherwise, it's the Forge version of GeckoLib and consequently Fabric won't load it.

**Comment by Cedesect** [comment]
> I had the same issue, just make sure that the filename of GeckoLib has _fabric_ in it. Otherwise, it's the Forge version of GeckoLib and consequently Fabric won't load it.
