### ISSUE TITLE
Rateline Elytrat Apears to Still not be Working

### ISSUE THREAD

**Issue by drzoidberg666** [Ladysnake/Rats-Mischief#68]
While the new update has seemed to fix the Elytrat textures for most of the named rats, Rateline has a default Elytrat texture instead of the trans flag texture
![2021-12-27_12 03 43](https://user-images.githubusercontent.com/54022995/147503783-6dcc888c-bfe8-4af9-895d-5eba11f71212.png)
.

**Comment by doctor4t** [comment]
Rateline never had a custom elytrat texture, but I guess it would fit so I will change that
