### ISSUE TITLE
[Crash] [1.18] REI Inspecio Incompatibility

### ISSUE THREAD

**Issue by greensad** [Ladysnake/Rats-Mischief#72]
### What's the issue you encountered?
With the mod Inspectio installed, as soon as I type any letter into REI search, I immediately get a crash.

### How can the issue be reproduced?
Launch the game -> Load a world -> Inventory -> type into REI box.

### Logs.
https://bytebin.lucko.me/f1KeO5ZrhI or https://crashy.net/Zqqkc2fWIMwP8BeBu1p5

### Mod Versions.
- Architectury 3.4.9
- Cloth Config 6.1.50
- Fabric Api 0.46.1
- Geckolib 3.0.27
- Inspecio 1.2.1
- Not Enough Crashes 4.1.4
- Rat's Mischief 1.3.4
- Roughly Enough Items 7.1.390

### Multi-MC Instance Link.
https://drive.google.com/file/d/1st32nZp8uXbWLDcIt0QXONuodkbN4jlN/view?usp=sharing

**Comment by MoriyaShiine** [comment]
https://github.com/Ladysnake/Rats-Mischief/commit/c88a47d2b09aa96e6bbc848b492e31023b76944e
