### ISSUE TITLE
Game crashes when spwning rat

### ISSUE THREAD

**Issue by TonicWater2006** [Ladysnake/Rats-Mischief#79]
I have been using Rats-Mischief for a long time now but recently i have downloaded game enhancing mods and it will no longer let me place the Rat. The game loads up fine and I can load up a new world. All the items can be held and used, but if a rat is placed the game will crash after around 2 seconds. Do you know if any of these mods are incompatible. I know I could get rid of the new mods, but with my trash PC it has really help improve my game play and allowed me to play on servers with my friends
![Screenshot (4)](https://user-images.githubusercontent.com/103083256/161875465-11a52d98-63b8-4092-be0b-1738a21acd6a.png)
![Screenshot (6)](https://user-images.githubusercontent.com/103083256/161875485-694ed12f-e825-4bc2-9d61-f8481f2b5aba.png)

**Comment by TonicWater2006** [comment]
The same thing happens with Pick Your Poison and another mod called Untitled Duck Mod It's the same scenario for all three

**Comment by Xiribidus** [comment]
No clue if thats whats causing it but you seem to have some duplicates of fapi and geckolib

**Comment by TonicWater2006** [comment]
OMG thank you so much it was the problem. I must have re downloaded them by accident. I would have never noticed thank you.
