### ISSUE TITLE
Rats spawning in inhabited villages?

### ISSUE THREAD

**Issue by IdrisQe** [Ladysnake/Rats-Mischief#8]
Not entirely sure why, but in my testing, Rats are actually spawning in and around (actually quite far out from) active villages that still have like 5+ villagers, beds, and houses. I'm using Overworld Two to generate the world, and have Charm which edits village houses a fair bit, but I don't think either should be causing this?

It's kind of a mess, since when farmer villages break/plant the crops, wild rats grab them and eat them, going into love mode, and ... For some reason breeding with my rats too. I went from having tamed like 4 rats, to suddenly having 7 by the time I left the village because they were breeding. Their wild population exploded too.

**Comment by doctor4t** [comment]
It's a known issue, will be fixed next version. Wild rats eating and breeding shouldn't be possible though, as rats only eat when they are hurt and wild rats are rarely hurt as nothing attacks them. Also, eating doesn't make them breed since it's just not how it works, so I'm not sure about that second problem, do you have vidéo proof?

**Comment by IdrisQe** [comment]
Afraid I don't have video proof. I really don't know how it happened, honestl-
**OH. WAIT.** It might be a mod interaction since I think I have a mod that makes animals eat off the ground.
I'll have to disable that setting, it's too dangerous. Sorry, I forgot that was a thing with ... at least one of the tweak-pack mods I have. Charm or Allure or VanillaTweaks or TinyTweaks or MiniExtras or something... So much feature overlap it may even be several of them.

I did notice some wild rats having low health oddly enough though. Not sure how they could have gotten damaged though. Maybe they walked into a cactus or something since it was near a desert? Which actually, I'm not sure if they are already but since they're naturally small and rats are known for living in thorny bushes and stuff, maybe making them immune to Cactus and Berry Bushes would be a good idea.
