### ISSUE TITLE
Server is crashing

### ISSUE THREAD

**Issue by TheButterbrotMan** [Ladysnake/Rats-Mischief#84]
https://bytebin.lucko.me/UPYrmOjvQ9

**Comment by TheButterbrotMan** [comment]
https://bytebin.lucko.me/nWO3lIE6ND

**Comment by xErrorAmelie** [comment]
Hey we have some players in AQM2 with the same issue. They crash every time they join a specific world, in this case it's the caving dimension from the Mining Dimensions mod.

Crashlog:
https://gist.github.com/itsdinkd/3888c1c1ed030a9c97cae2e288656a4d

**Comment by xErrorAmelie** [comment]
It happend to another player in the overworld when he loads a chunk that contains spawning rats it seems?

Crashlog:
https://mclo.gs/xOqV18T

**Comment by xErrorAmelie** [comment]
Another one while exploring overworld: https://crashy.net/EjvUHTr9uL12g2n93nmX
I will end that, there are enough reports now xD
