### ISSUE TITLE
Looking at rats drops FPS considerably

### ISSUE THREAD

**Issue by VallenFrostweaver** [Ladysnake/Rats-Mischief#88]
Minecraft 1.18.1
Fabric 0.13.3
Rat's Mischief 1.3.4
Modpack: Benchmark II version 1.0.7

When looking directly at a rat the FPS drops considerably but looking near it doesn't have an effect. See images for details. Tested on 2 different PC's with a fresh download of the pack.
![2022-05-18_18 50 52](https://user-images.githubusercontent.com/13642054/169109727-6b40a0ea-699b-4b8a-b46f-0c5703f96bbf.png)
![2022-05-18_18 51 12](https://user-images.githubusercontent.com/13642054/169109754-4ba05452-b2ac-4ea4-9601-a568bc001a77.png)
.

**Comment by doctor4t** [comment]
Not sure what could be causing this, not experiencing in 2.0
