### ISSUE TITLE
Request: Keybind/Item to set rats to "lazy" mode

### ISSUE THREAD

**Issue by IdrisQe** [Ladysnake/Rats-Mischief#9]
Having rats is great, but also a pain when you're trying to do a lot of things... Especially if you have more rats than you have pouch space. Getting rid of items early-game is near impossible without going around and making sure all your rats are sitting first, since they'll just bring them back to you, nevermind if you're passing through a village you'll end up with all the Farmer's crops. Also they seem to replant saplings naturally... Unless that's another mod I'm using and it's just looking like my Rats are doing it.

It would be nice if there was a keybind (or an easy-to-craft item like a ... I dunno... Rat Whistle, or something) which would set all your Rats into "lazy mode" where they'll follow you but not do much else. If going the item route, also maybe shift+right clicking would make all Rats sit down, then make them all stand up and call them to you (since it's way too easy currently to accidentally lose a rat if you right click them by mistake in the middle of a grass field)

**Comment by doctor4t** [comment]
I had planned to do something like a sitting staff. Shift click would sit all the rats, while a normal click would unsit them all. But maybe a staff would be too hard to get for what it does?

Rats don't plant saplings on my end, so most likely another mod doing that.

Maybe a craftable early game item to choose what mode rats are on? But I don't think it would be justified for just a "bring items or not" config; maybe I could also add a combat setting (like passive, normal, and attack any hostile), as well as a "eat and heal" setting? I'd be down to add an item like that, what do you think could be other interesting parameters the player could set with that item if you have ideas?

**Comment by IdrisQe** [comment]
Maybe a setting that makes them attempt to spread out like normal vs. try to group together near you? Not sure if the pathing AI would cooperate with that but it could be useful for when you're trying to get your rats into a bag, or trying to get them to all come inside with you.

**Comment by avetharun** [comment]
Sorry for necro, but this is just too good of an idea. Possibly the item that could be used, is a carrot. Give em something to munch on and in exchange they'll sit and do nothing until you right click (like a normal tamed mob)

They'll passively play quiet, higher pitched eating sounds, and act like they're eating. I could try to make this happen if you'd like
