### ISSUE TITLE
Ticking Entity Error While Breeding Rats

### ISSUE THREAD

**Issue by BearfootNick** [Ladysnake/Rats-Mischief#90]
Server Crashed while breeding rats creating a ticking entity. Looks like a unique id was copied instead of a new one being created?

Fabric 13.3
Minecraft 1.18.1

[Rats Crash - Server.txt](https://github.com/Ladysnake/Rats-Mischief/files/9058264/Rats.Crash.-.Server.txt)

**Comment by MoriyaShiine** [comment]
Clone of #74
