### ISSUE TITLE
(1.19) Rats Mischief crash on server starting up - "EntityCondition json type "ratsmischief:enable_rat" is not defined"

### ISSUE THREAD

**Issue by jaredniegas** [Ladysnake/Rats-Mischief#92]
I have no idea what's causing this. I hope this can be fixed soon!

[latest.log](https://github.com/Ladysnake/Rats-Mischief/files/9152830/latest.log)

**Comment by MaoMaoMcMao** [comment]
I have the same issue, and it occurs on both the versions of 1.19.

**Comment by una-mura** [comment]
exactly the same here on client version
