### ISSUE TITLE
New rat easter egg to remember my pet who just passed (Suggestion)

### ISSUE THREAD

**Issue by Xfrtrex** [Ladysnake/Rats-Mischief#95]
yesterday one of my pet rats named "Maple" died, one of the sweetest rats ever, I think there should be an easter egg to remember her.
if you don't want to I understand.
i have made a texture:
![maple](https://user-images.githubusercontent.com/80720298/184463149-6672168c-910d-41e4-86dd-c7666b1bfa05.png)
and here is Maple
![image](https://user-images.githubusercontent.com/80720298/184462793-91fdf728-3985-47ad-8dd3-4f5117d92a87.png)

**Comment by Specimen-420** [comment]
Rip Maple

**Comment by doctor4t** [comment]
I never check issues, sorry I missed this. I'm late now, but I'm sorry for your loss. However, I don't think I can add other people's pets cause more people will then ask and it'll get out of hand. You could make an addon to have that feature if you wanted.
